name: 🚀 Update Profile & Generate Snake

on:
  schedule:
    - cron: "0 * * * *" # Runs every 1 hours
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main # Runs on every push to main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permission to write to the repository
    steps:
      # Checkout repository to access files
      - name: 📋 Checkout
        uses: actions/checkout@v4

      # Generate Snake Animation (SVG only, no GIF)
      - name: 🐍 Generate Snake (SVG only)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SooYungTing # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-rainbow.svg?palette=github-dark&color_snake=rainbow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

      # Publish the generated SVGs to the `output` branch
      - name: 🚀 Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # The branch to commit the files to
          build_dir: dist # Directory where the SVGs are located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

  # Job for updating WakaTime stats (optional, you can disable this if not used)
  update-waka:
    name: 📊 Update WakaTime Stats
    runs-on: ubuntu-latest
    continue-on-error: true # Continue even if this step fails

    steps:
      - name: 📋 Checkout
        uses: actions/checkout@v4

      - name: ⏰ Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
        continue-on-error: true # Continue even if this step fails

  # Optional metrics generation
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SooYungTing # Replace with your GitHub username
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Singapore
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
        continue-on-error: true # Continue even if this step fails
